# Generated by Django 3.1.1 on 2021-02-24 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapplication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='instituition',
            new_name='institution',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='phone',
        ),
    ]
